### ISSUE TITLE
Running on standard FJSP datasets/files

### ISSUE THREAD

**Issue by Akhilnandh** [wyh-neophyte/Metaheuristic-Algorithms-For-JSP-and-FJSP-Problems#1]
Hi there,

How can we run your code on standard test instances for benchmarking?

**Comment by Akhilnandh** [comment]
Please provide files of Brandimarte's and othr test instances in the way your code should read.

**Comment by Akhilnandh** [comment]
Also, what paper is your work based on?

**Comment by yiheng-wang-duke** [comment]
Actually, this repo is based on our own understanding, so the implementation might differ from other papers.

**Comment by wyh-neophyte** [comment]
Given mk01 case in txt file:
Jm ={ [1,3],[5,3,2],[3,6],[6,2,1],3,[6,3,4];
2,3,1,[2,4],[6,2,1];
2,[3,6],[6,2,1],[3,2,6],[1,5];
[6,2,1],2,3,[5,3,2],[3,6];
[5,3,2],[6,2,1],2,[1,3],[2,4],[3,2,6];
[3,6],1,[3,2,6],2,[6,2,1],[1,4];
6,[1,4],[3,2,6],[2,5,1],3;
[3,6],[3,2,6],[6,2,1],2,[2,4];
6,[1,5],[6,3,4],1,[3,2,6],[2,4];
[3,6],[3,2,6],[5,3,2],6,[2,4],[1,4]};

T = {[5,4],[3,5,1],[4,2],[5,6,1],1,[6,6,3];
6,1,2,[6,6],[5,6,1];
6,[4,2],[5,6,1],[4,6,6],[1,5];
[5,6,1],6,1,[3,5,1],[4,2];
[3,5,1],[5,6,1],6,[5,4],[6,6],[4,6,6];
[4,2],2,[4,6,6],6,[5,6,1],[3,2];
1,[3,2],[4,6,6],[6,1,6],1;
[4,2],[4,6,6],[5,6,1],6,[6,6];
1,[1,5],[6,6,3],2,[4,6,6],[6,6];
[4,2],[4,6,6],[3,5,1],1,[6,6],[3,2]};

You can process it with the following code:
import re
import json

with open('mk01.txt', 'r') as file:
    lines = file.readlines()
lines = [line.strip() for line in lines]
data = ''.join(lines)

# match jm
match = re.search(r'Jm\s*=\s*\{(.*?)\}\s*;', data, re.DOTALL)
if match:
    Jm = match.group(1).strip()
Jm = Jm.split(';')
print(Jm)

# match T
match = re.search(r'T\s*=\s*\{(.*)\}', data, re.DOTALL)
if match:
    T = match.group(1).strip()
T = T.split(';')
print(T)

# process jm to python list
for idx, _Jm in enumerate(Jm):
    matches = re.findall(r'\[(.*?)\]|(\d+)', _Jm)
    result = []
    for match in matches:
        if match[0]:
            result.append([int(x) for x in match[0].split(',')])
        else:
            result.append([int(match[1])])
    Jm[idx] = result
print(Jm)
print(len(Jm))

# process T to python list
for idx, _T in enumerate(T):
    matches = re.findall(r'\[(.*?)\]|(\d+)', _T)
    result = []
    for match in matches:
        if match[0]:
            result.append([int(x) for x in match[0].split(',')])
        else:
            result.append([int(match[1])])
    T[idx] = result
print(T)
print(len(T))

# process the information to json
info_dict = {}
machine_list = []
for workpiece_id in range(len(Jm)):
    info_dict[str(workpiece_id)] = {}
    for process_id in range(len(Jm[workpiece_id])):
        info_dict[str(workpiece_id)][str(process_id)] = []
        try:
            for available_machine_id, time_cost in zip(Jm[workpiece_id][process_id], T[workpiece_id][process_id]):

                # note that in our code, machine id starts with 0, ...
                info_dict[str(workpiece_id)][str(process_id)].append([available_machine_id - 1, time_cost])
                if available_machine_id not in machine_list:
                    machine_list.append(available_machine_id)
        except:
            print(f'error with workpiece_id:{workpiece_id}, process_id:{process_id}')

info_dict["partnum"] = len(Jm)
info_dict["machinenum"] = len(machine_list)

with open('../data/data.json', 'w') as file:
    json.dump(info_dict, file)

**Comment by wyh-neophyte** [comment]
Given mk01 in txt format:
`Jm ={ [1,3],[5,3,2],[3,6],[6,2,1],3,[6,3,4];
2,3,1,[2,4],[6,2,1];
2,[3,6],[6,2,1],[3,2,6],[1,5];
[6,2,1],2,3,[5,3,2],[3,6];
[5,3,2],[6,2,1],2,[1,3],[2,4],[3,2,6];
[3,6],1,[3,2,6],2,[6,2,1],[1,4];
6,[1,4],[3,2,6],[2,5,1],3;
[3,6],[3,2,6],[6,2,1],2,[2,4];
6,[1,5],[6,3,4],1,[3,2,6],[2,4];
[3,6],[3,2,6],[5,3,2],6,[2,4],[1,4]};

T = {[5,4],[3,5,1],[4,2],[5,6,1],1,[6,6,3];
6,1,2,[6,6],[5,6,1];
6,[4,2],[5,6,1],[4,6,6],[1,5];
[5,6,1],6,1,[3,5,1],[4,2];
[3,5,1],[5,6,1],6,[5,4],[6,6],[4,6,6];
[4,2],2,[4,6,6],6,[5,6,1],[3,2];
1,[3,2],[4,6,6],[6,1,6],1;
[4,2],[4,6,6],[5,6,1],6,[6,6];
1,[1,5],[6,6,3],2,[4,6,6],[6,6];
[4,2],[4,6,6],[3,5,1],1,[6,6],[3,2]};
`

You can process it with the following code:
`import re
import json

with open('mk01.txt', 'r') as file:
    lines = file.readlines()
lines = [line.strip() for line in lines]
data = ''.join(lines)

# match jm
match = re.search(r'Jm\s*=\s*\{(.*?)\}\s*;', data, re.DOTALL)
if match:
    Jm = match.group(1).strip()
Jm = Jm.split(';')
print(Jm)

# match T
match = re.search(r'T\s*=\s*\{(.*)\}', data, re.DOTALL)
if match:
    T = match.group(1).strip()
T = T.split(';')
print(T)

# process jm to python list
for idx, _Jm in enumerate(Jm):
    matches = re.findall(r'\[(.*?)\]|(\d+)', _Jm)
    result = []
    for match in matches:
        if match[0]:
            result.append([int(x) for x in match[0].split(',')])
        else:
            result.append([int(match[1])])
    Jm[idx] = result
print(Jm)
print(len(Jm))

# process T to python list
for idx, _T in enumerate(T):
    matches = re.findall(r'\[(.*?)\]|(\d+)', _T)
    result = []
    for match in matches:
        if match[0]:
            result.append([int(x) for x in match[0].split(',')])
        else:
            result.append([int(match[1])])
    T[idx] = result
print(T)
print(len(T))

# process the information to json
info_dict = {}
machine_list = []
for workpiece_id in range(len(Jm)):
    info_dict[str(workpiece_id)] = {}
    for process_id in range(len(Jm[workpiece_id])):
        info_dict[str(workpiece_id)][str(process_id)] = []
        try:
            for available_machine_id, time_cost in zip(Jm[workpiece_id][process_id], T[workpiece_id][process_id]):

                # note that in our code, machine id starts with 0, ...
                info_dict[str(workpiece_id)][str(process_id)].append([available_machine_id - 1, time_cost])
                if available_machine_id not in machine_list:
                    machine_list.append(available_machine_id)
        except:
            print(f'error with workpiece_id:{workpiece_id}, process_id:{process_id}')

info_dict["partnum"] = len(Jm)
info_dict["machinenum"] = len(machine_list)

with open('../data/data.json', 'w') as file:
    json.dump(info_dict, file)

`

**Comment by wyh-neophyte** [comment]
Given mk01 in txt format:
Jm ={ [1,3],[5,3,2],[3,6],[6,2,1],3,[6,3,4];
2,3,1,[2,4],[6,2,1];
2,[3,6],[6,2,1],[3,2,6],[1,5];
[6,2,1],2,3,[5,3,2],[3,6];
[5,3,2],[6,2,1],2,[1,3],[2,4],[3,2,6];
[3,6],1,[3,2,6],2,[6,2,1],[1,4];
6,[1,4],[3,2,6],[2,5,1],3;
[3,6],[3,2,6],[6,2,1],2,[2,4];
6,[1,5],[6,3,4],1,[3,2,6],[2,4];
[3,6],[3,2,6],[5,3,2],6,[2,4],[1,4]};

T = {[5,4],[3,5,1],[4,2],[5,6,1],1,[6,6,3];
6,1,2,[6,6],[5,6,1];
6,[4,2],[5,6,1],[4,6,6],[1,5];
[5,6,1],6,1,[3,5,1],[4,2];
[3,5,1],[5,6,1],6,[5,4],[6,6],[4,6,6];
[4,2],2,[4,6,6],6,[5,6,1],[3,2];
1,[3,2],[4,6,6],[6,1,6],1;
[4,2],[4,6,6],[5,6,1],6,[6,6];
1,[1,5],[6,6,3],2,[4,6,6],[6,6];
[4,2],[4,6,6],[3,5,1],1,[6,6],[3,2]};

You can process it with code:
import re
import json

with open('mk01.txt', 'r') as file:
    lines = file.readlines()
lines = [line.strip() for line in lines]
data = ''.join(lines)


match = re.search(r'Jm\s*=\s*\{(.*?)\}\s*;', data, re.DOTALL)# match jm
if match:
    Jm = match.group(1).strip()
Jm = Jm.split(';')
print(Jm)


match = re.search(r'T\s*=\s*\{(.*)\}', data, re.DOTALL)# match T
if match:
    T = match.group(1).strip()
T = T.split(';')
print(T)


for idx, _Jm in enumerate(Jm): # process jm to python list
    matches = re.findall(r'\[(.*?)\]|(\d+)', _Jm)
    result = []
    for match in matches:
        if match[0]:
            result.append([int(x) for x in match[0].split(',')])
        else:
            result.append([int(match[1])])
    Jm[idx] = result
print(Jm)
print(len(Jm))


for idx, _T in enumerate(T): # process T to python list
    matches = re.findall(r'\[(.*?)\]|(\d+)', _T)
    result = []
    for match in matches:
        if match[0]:
            result.append([int(x) for x in match[0].split(',')])
        else:
            result.append([int(match[1])])
    T[idx] = result
print(T)
print(len(T))

info_dict = {} # process the information to json
machine_list = []
for workpiece_id in range(len(Jm)):
    info_dict[str(workpiece_id)] = {}
    for process_id in range(len(Jm[workpiece_id])):
        info_dict[str(workpiece_id)][str(process_id)] = []
        try:
            for available_machine_id, time_cost in zip(Jm[workpiece_id][process_id], T[workpiece_id][process_id]):

                # note that in our code, machine id starts with 0, ...
                info_dict[str(workpiece_id)][str(process_id)].append([available_machine_id - 1, time_cost])
                if available_machine_id not in machine_list:
                    machine_list.append(available_machine_id)
        except:
            print(f'error with workpiece_id:{workpiece_id}, process_id:{process_id}')

info_dict["partnum"] = len(Jm)
info_dict["machinenum"] = len(machine_list)

with open('../data/data.json', 'w') as file:
    json.dump(info_dict, file)

**Comment by yiheng-wang-duke** [comment]
Given mk01 in txt format, 
[mk01.txt](https://github.com/user-attachments/files/16885323/mk01.txt)
you can process it with the code
[to_json.zip](https://github.com/user-attachments/files/16885335/to_json.zip)
